# lab_simpsons-paradox

Hi Data Scientists,

Welcome to the third lab!  In this lab, you will explore using pandas to explore real-word datasets and find if Simpson's Paradox appears in several different datasets.


### Labs are Collaborative

In your lab section (right now!), find a person or two around you and form a group.  Work on this together, making sure all of you understand each component of the lab.


### Getting Help

Remember, there are a lot of ways to get help if you find yourself stuck:

1. In lab section, your TA, CAs, and your peers are here for you!


2. On the course Piazza page: https://piazza.com/illinois/fall2019/stat107


3. Office Hours:

  - Open office hours **every Monday, Wednesday, Thursday, and Friday** from 4:00pm - 6:30pm in 23 Illini Hall

  - Prof. Wade + Prof. Karle are available every Wednesday from 8:30am - 10:00am in 2215 Siebel Center

# Puzzle 1: Homecoming Date Night

Imagine you and your partner are trying to find the perfect restaurant for a homecoming date night dinner!  Knowing this process can lead to hours of arguments, you seek out the answer to all of life’s questions: *online reviews*. 

The dataset `Black Dog Reviews.csv` (already provided for you as part of the lab code you checked out from git) contains data showing all of the males and females that have reviewed Black Dog in the past year and whether or not they recommended it.  The dataset `Papa Dels Reviews.csv` contains the same information for Papa Dels.


## 1.1: Data Cleaning

Unfortunately, this data was not as tidy as all of our data has been so far. :(

- Open `Black Dog Reviews.csv` and `Papa Dels Reviews.csv` CSV file using any program that can edit spreadsheets.  This can be Microsoft Excel (if you have it installed) or you can upload it to Google Drive and edit it with Google Sheets.
- Modify the file to ensure all rows that in the `Gender` column has the same value for the two gender categories (as `Male` and `Female`) found in this dataset.
- Finally, make sure to save the file as a CSV so you can used your cleaned dataset for this lab.


## 1.2. Loading Your DataSet

Load the DataSets you just cleaned into Python:

In [5]:
# Import the pandas library as pd
import pandas as pd

In [14]:
df_black_dog = pd.read_csv("Black Dog Reviews.csv")
df_black_dog

    Gender Recommend Black Dog
0     Male                 Yes
1     Male                 Yes
2     Male                 Yes
3     Male                 Yes
4     Male                 Yes
5     Male                  No
6     Male                  No
7     Male                  No
8     Male                  No
9     Male                  No
10    Male                  No
11    Male                  No
12    Male                  No
13    Male                  No
14    Male                  No
15  Female                 Yes
16  Female                 Yes
17  Female                 Yes
18  Female                 Yes
19  Female                 Yes
20  Female                 Yes
21  Female                 Yes
22  Female                 Yes
23  Female                 Yes
24  Female                 Yes
25  Female                 Yes
26  Female                 Yes
27  Female                 Yes
28  Female                 Yes
29  Female                 Yes
30  Female                 Yes
31  Female                 Yes
32  Female                 Yes
33  Female                 Yes
34  Female                 Yes
35  Female                  No
36  Female                  No
37  Female                  No
38  Female                  No
39  Female                  No

In [7]:
## == TEST CASES for Puzzle 1.2 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(len(df_black_dog) == 40), "The dataframe does not appear to have correct dataset loaded"

In [9]:
df_papa_del = pd.read_csv("Papa Dels Reviews.csv")
df_papa_del

    Gender Recommend Papa Dels
0     Male                 Yes
1     Male                 Yes
2     Male                 Yes
3     Male                 Yes
4     Male                 Yes
5     Male                 Yes
6     Male                 Yes
7     Male                 Yes
8     Male                 Yes
9     Male                 Yes
10    Male                 Yes
11    Male                 Yes
12    Male                 Yes
13    Male                 Yes
14    Male                 Yes
15    Male                 Yes
16    Male                 Yes
17    Male                 Yes
18    Male                  No
19    Male                  No
20    Male                  No
21    Male                  No
22    Male                  No
23    Male                  No
24    Male                  No
25    Male                  No
26    Male                  No
27    Male                  No
28    Male                  No
29    Male                  No
30    Male                  No
31    Male                  No
32    Male                  No
33    Male                  No
34    Male                  No
35    Male                  No
36  Female                 Yes
37  Female                 Yes
38  Female                 Yes
39  Female                 Yes
40  Female                 Yes
41  Female                 Yes
42  Female                 Yes
43  Female                 Yes
44  Female                 Yes
45  Female                  No

In [10]:
## == TEST CASES for Puzzle 1.2 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(len(df_papa_del) == 46), "The dataframe does not appear to have correct dataset loaded"

## 1.3. Analysis

We want to use the Black Dog dataset to calculate the percentage of women who recommended Black Dog.  Then calculate the percentage of men who recommended Black Dog:

In [15]:
black_dog_female = df_black_dog[df_black_dog['Gender'] == 'Female']
black_dog_femaleY = black_dog_female[black_dog_female['Recommend Black Dog'] == 'Yes']
black_dog_female_percent = len(black_dog_femaleY)/len(black_dog_female)
black_dog_female_percent

0.8

In [ ]:
## == TEST CASES for Puzzle 1.3 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(black_dog_female_percent == 0.8), "The percentage of Female who recommended Black Dog does not appear to have correct calculated"

In [16]:
black_dog_male = df_black_dog[df_black_dog['Gender'] == 'Male']
black_dog_maleY = black_dog_male[black_dog_male['Recommend Black Dog'] == 'Yes']

black_dog_male_percent = len(black_dog_maleY)/len(black_dog_male)
black_dog_male_percent

0.3333333333333333

In [17]:
## == TEST CASES for Puzzle 1.3 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(black_dog_male_percent == (1/3)), "The percentage of Male who recommended Black Dog does not appear to have correct calculated"

Similarly, use the Papa Dels dataset to calculate the percentage of women who recommended Papa Dels.  Then calculate the percentage of men who recommended Papa Dels:

In [19]:
papa_dels_female = df_papa_del[df_papa_del['Gender'] == 'Female']
papa_dels_femaleY = papa_dels_female[papa_dels_female['Recommend Papa Dels'] == "Yes"]

papa_dels_female_percent = len(papa_dels_femaleY)/len(papa_dels_female)
papa_dels_female_percent

0.9

In [20]:
## == TEST CASES for Puzzle 1.3 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(papa_dels_female_percent == 0.9), "The percentage of Female who recommended Papa Dels does not appear to have correctly calculated"

In [21]:
papa_dels_male = df_papa_del[df_papa_del['Gender'] == 'Male']
papa_dels_maleY = papa_dels_male[papa_dels_male['Recommend Papa Dels'] == "Yes"]

papa_dels_male_percent = len(papa_dels_maleY)/len(papa_dels_male)
papa_dels_male_percent

0.5

In [22]:
## == TEST CASES for Puzzle 1.3 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(papa_dels_male_percent == 0.5), "The percentage of Male who recommended Papa Dels does not appear to have correct calculated"

### Observe the Results

Run the following cell to format all of your answers as a DataFrame:

In [23]:
pd.DataFrame( [
    {'Female': black_dog_female_percent, 'Male': black_dog_male_percent },
    {'Female': papa_dels_female_percent, 'Male': papa_dels_male_percent },    
], index=['Black Dog', 'Papa Dels'])

           Female      Male
Black Dog     0.8  0.333333
Papa Dels     0.9  0.500000

❓ **Question** ❓: Should your homecoming date night be at Black Dog or Papa Dels?

- Dows "Black Dog" (Row #1) have higher values or "Papa Dels" (Row #2) have higher values?

## 1.4. Analysis - Part 2

For our final analysis, let's examine the **overall** percentage of people who recommend each restaurant:

In [24]:
black_dogY = df_black_dog[df_black_dog['Recommend Black Dog'] == 'Yes']
black_dog_recommended_percent = len(black_dogY)/len(df_black_dog)
black_dog_recommended_percent

0.625

In [25]:
## == TEST CASES for Puzzle 1.4 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(black_dog_recommended_percent == 0.625), "The percentage of Overall who recommended Black Dog does not appear to have correct calculated"

In [26]:
papa_delsY = df_papa_del[df_papa_del["Recommend Papa Dels"] == 'Yes']

papa_dels_recommended_percent = len(papa_delsY)/len(df_papa_del) 
papa_dels_recommended_percent

0.5869565217391305

In [27]:
## == TEST CASES for Puzzle 1.4 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(papa_dels_recommended_percent == (27/46)), "The percentage of Overall who recommended Papa Dels does not appear to have correct calculated"

### Observe the Results

Run the following cell to format all of your answers as a DataFrame:

In [28]:
pd.DataFrame( [
    {'Female': black_dog_female_percent, 'Male': black_dog_male_percent, 'Overall': black_dog_recommended_percent },
    {'Female': papa_dels_female_percent, 'Male': papa_dels_male_percent, 'Overall': papa_dels_recommended_percent },
], index=['Black Dog', 'Papa Dels'] )

           Female      Male   Overall
Black Dog     0.8  0.333333  0.625000
Papa Dels     0.9  0.500000  0.586957

❓ **Question** ❓: Should your homecoming date night be at Black Dog or Papa Dels?

- Dows "Black Dog" (Row #1) have higher values or "Papa Dels" (Row #2) have higher values for **Overall**?

# Puzzle 2: Twitch and Shoes

From the "Hello" dataset we created on the first day of class, we picked two random questions for us to explore:

- Do you view video on Twitch at least once a week?
- How many pairs of shoes do you have?

## 2.1: Load the Dataset

- You can find the "Hello" dataset here (make sure to log in with your @illinois.edu address to access it): https://docs.google.com/spreadsheets/d/1LB4E89GoVi5yezEfHhopbI5BMxodSG7VvoznkaAkMAQ/edit#gid=0

In [34]:
# Read the hello dataset into a DataFrame
df_hello = pd.read_csv('hello.csv')
df_hello

,Name,Major,School Year,Type,Computer,Straw Holes,Has Dogs,Has Cats,Has Fish,Has Chickens,...,Has Twitch,Programmed before?,Python Background,Statistics Courses,Hours Studying,Siblings,Hours of Sleep,Shoes Owned,People Texted Yesterday,Personality
0,Wade,Computer Science,Other,Android,Windows-based computer,2.0,0,1,0,0,...,0,Yes,Significant -- I am a wizard when it comes to ...,2,3.0,2.0,8.0,4.0,2.0,Introvert
1,Karle,Statistics,Other,iPhone,Mac OS X-based computer,1.0,0,0,0,0,...,0,Yes,Some Python -- I have had one class or written...,20,1.0,2.0,7.0,20.0,24.0,Extrovert
2,noor,global studies/statistics,Sophomore,iPhone,Mac OS X-based computer,1.0,0,0,0,0,...,0,No,No programming background -- is Python Taylor ...,3,3.0,1.0,7.0,20.0,10.0,Introvert
3,Jonathan,Political Science,Senior,iPhone,Mac OS X-based computer,1.0,1,1,0,0,...,0,Yes,"No Python, but I've done some programming in o...",2,4.0,1.0,6.0,10.0,8.0,Introvert
4,Clare,Statistics,Sophomore,iPhone,Mac OS X-based computer,1.0,1,0,0,0,...,0,Yes,Some Python -- I have had one class or written...,1,4.0,0.0,8.0,20.0,30.0,Ambivert
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,Stephanie,Political Science,Junior,iPhone,Mac OS X-based computer,NaN,1,0,0,0,...,0,No,No programming background -- is Python Taylor ...,1,2.0,9.0,7.0,30.0,12.0,Extrovert
162,Cindy,biomedical engineering,Senior,Android,Windows-based computer,1.0,1,0,0,0,...,0,No,"No Python, but I've done some programming in o...",1,2.0,1.0,8.0,3.0,8.0,Ambivert
163,Talal,Information sciences,Sophomore,iPhone,Windows-based computer,1.0,0,1,0,0,...,0,Yes,"No Python, but I've done some programming in o...",0,3.0,2.0,8.0,12.0,25.0,Ambivert
164,John,Statistics or Business,Freshman,iPhone,Windows-based computer,1.0,1,0,0,0,...,1,No,No programming background -- is Python Taylor ...,1,1.0,1.0,7.0,12.0,60.0,Introvert
165,Anisha,Mcb,Junior,iPhone,Mac OS X-based computer,1.0,0,0,0,0,...,0,Yes,Some Python -- I have had one class or written...,1,4.0,1.0,7.0,6.0,15.0,Introvert

In [35]:
## == TEST CASES for Puzzle 2.1 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(len(df_hello) == 166), "The dataframe does not appear to have correct dataset loaded"

## 2.2: Observation Subsets

Create two DataFrames that contain subsets of our data: one DataFrame that includes everyone who has watches Twitch at least once a week and one DataFrame that includes everyone who does not watch twitch at least once a week:

In [37]:
df_twitch = df_hello[df_hello['Has Twitch'] == 1]
df_twitch

,Name,Major,School Year,Type,Computer,Straw Holes,Has Dogs,Has Cats,Has Fish,Has Chickens,...,Has Twitch,Programmed before?,Python Background,Statistics Courses,Hours Studying,Siblings,Hours of Sleep,Shoes Owned,People Texted Yesterday,Personality
5,Dhruv,Computer science,Sophomore,Android,Windows-based computer,1.0,0,0,0,0,...,1,Yes,Some Python -- I have had one class or written...,0,3.0,2.0,6.0,4.0,11.0,Introvert
9,Edward/Edd,"CS, business data analysis?",Senior,Android,Linux-based computer,1.0,0,0,0,0,...,1,Yes,Some Python -- I have had one class or written...,1,3.0,2.0,8.0,5.0,10.0,Ambivert
10,Taige,Math + CS,Freshman,iPhone,Windows-based computer,1.0,0,1,0,0,...,1,Yes,Some Python -- I have had one class or written...,4,3.0,0.0,6.0,6.0,15.0,Introvert
13,Andy,Statistics,Senior,iPhone,Windows-based computer,1.0,0,0,0,0,...,1,Yes,Some Python -- I have had one class or written...,3,10.0,2.0,7.0,3.0,70.0,Ambivert
44,Andrew,CS + STAT,Junior,iPhone,Windows-based computer,1.0,1,1,0,0,...,1,Yes,"No Python, but I've done some programming in o...",4,4.0,1.0,5.0,2.0,2.0,Ambivert
45,Leo,CS?,Freshman,iPhone,Windows-based computer,1.0,0,0,1,0,...,1,Yes,Some Python -- I have had one class or written...,0,3.0,1.0,8.5,3.0,20.0,Ambivert
51,Zhoutian,Computer Engineering,Freshman,iPhone,Windows-based computer,1.0,0,0,1,0,...,1,Yes,"No Python, but I've done some programming in o...",1,9.0,0.0,7.0,6.0,6.0,Ambivert
61,Tyler,actuarial science,Freshman,Android,Windows-based computer,1.0,1,1,0,0,...,1,Yes,Some Python -- I have had one class or written...,2,3.0,3.0,8.0,5.0,10.0,Introvert
67,Vivek,Computer science,Sophomore,iPhone,Windows-based computer,2.0,0,0,1,0,...,1,Yes,Some Python -- I have had one class or written...,0,3.0,1.0,6.0,4.0,30.0,Extrovert
77,Michael,Actuarial Science,Senior,Android,Windows-based computer,1.0,0,0,0,0,...,1,Yes,Some Python -- I have had one class or written...,2,1.0,2.0,8.0,6.0,9.0,Ambivert
90,Stephen,Psychology & Computer Science,Freshman,Android,Mac OS X-based computer,2.0,1,1,0,0,...,1,Yes,Some Python -- I have had one class or written...,0,10.0,0.0,7.5,2.0,8.0,Introvert
103,Cole,Political Science,Junior,iPhone,Mac OS X-based computer,1.0,1,0,0,0,...,1,Yes,"No Python, but I've done some programming in o...",2,4.0,1.0,6.0,11.0,3.0,Introvert
126,Jaesung,Economics,Senior,iPhone,Mac OS X-based computer,1.0,0,0,0,0,...,1,Yes,"No Python, but I've done some programming in o...",3,12.0,2.0,7.0,5.0,3.0,Introvert
129,Miles,GIS,Senior,iPhone,Windows-based computer,0.0,1,1,0,1,...,1,Yes,Some Python -- I have had one class or written...,1,1.0,0.0,7.0,3.0,10.0,Ambivert
141,Andi,Computer Science + Statistics or Statistics ma...,Sophomore,iPhone,Windows-based computer,1.0,1,0,0,0,...,1,Yes,Some Python -- I have had one class or written...,2,1.0,1.0,6.0,3.0,10.0,Introvert
142,Jason,History,Senior,Android,Windows-based computer,1.0,1,0,0,0,...,1,Yes,Some Python -- I have had one class or written...,1,1.0,1.0,7.0,2.0,1.0,Introvert
143,Austin,Computer Science and Linguistics,Junior,Android,Windows-based computer,1.0,0,0,1,0,...,1,Yes,Significant -- I am a wizard when it comes to ...,2,3.0,1.0,7.0,2.0,3.0,Introvert
148,Matt,Information Sciences,Sophomore,Android,Linux-based computer,1.0,0,0,0,0,...,1,Yes,Some Python -- I have had one class or written...,1,4.0,2.0,10.0,6.0,15.0,Ambivert
154,David,Information Sciences,Sophomore,Android,Windows-based computer,1.0,1,1,0,0,...,1,Yes,"No Python, but I've done some programming in o...",0,2.5,2.0,6.0,1.0,3.0,Ambivert
160,Nate,Statistics,Sophomore,iPhone,Windows-based computer,1.0,1,0,0,0,...,1,Yes,"No Python, but I've done some programming in o...",1,8.0,4.0,8.0,12.0,100.0,Ambivert
164,John,Statistics or Business,Freshman,iPhone,Windows-based computer,1.0,1,0,0,0,...,1,No,No programming background -- is Python Taylor ...,1,1.0,1.0,7.0,12.0,60.0,Introvert

In [38]:
## == TEST CASES for Puzzle 2.2 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(len(df_twitch) == 21), "The dataframe does not appear to have been correct subset"

In [39]:
df_no_twitch = df_hello[df_hello['Has Twitch'] == 0]
df_no_twitch

,Name,Major,School Year,Type,Computer,Straw Holes,Has Dogs,Has Cats,Has Fish,Has Chickens,...,Has Twitch,Programmed before?,Python Background,Statistics Courses,Hours Studying,Siblings,Hours of Sleep,Shoes Owned,People Texted Yesterday,Personality
0,Wade,Computer Science,Other,Android,Windows-based computer,2.0,0,1,0,0,...,0,Yes,Significant -- I am a wizard when it comes to ...,2,3.0,2.0,8.0,4.0,2.0,Introvert
1,Karle,Statistics,Other,iPhone,Mac OS X-based computer,1.0,0,0,0,0,...,0,Yes,Some Python -- I have had one class or written...,20,1.0,2.0,7.0,20.0,24.0,Extrovert
2,noor,global studies/statistics,Sophomore,iPhone,Mac OS X-based computer,1.0,0,0,0,0,...,0,No,No programming background -- is Python Taylor ...,3,3.0,1.0,7.0,20.0,10.0,Introvert
3,Jonathan,Political Science,Senior,iPhone,Mac OS X-based computer,1.0,1,1,0,0,...,0,Yes,"No Python, but I've done some programming in o...",2,4.0,1.0,6.0,10.0,8.0,Introvert
4,Clare,Statistics,Sophomore,iPhone,Mac OS X-based computer,1.0,1,0,0,0,...,0,Yes,Some Python -- I have had one class or written...,1,4.0,0.0,8.0,20.0,30.0,Ambivert
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,Julisa,Mathematics,Sophomore,iPhone,Windows-based computer,2.0,0,0,0,0,...,0,Yes,Some Python -- I have had one class or written...,0,3.0,3.0,5.0,10.0,15.0,Extrovert
161,Stephanie,Political Science,Junior,iPhone,Mac OS X-based computer,NaN,1,0,0,0,...,0,No,No programming background -- is Python Taylor ...,1,2.0,9.0,7.0,30.0,12.0,Extrovert
162,Cindy,biomedical engineering,Senior,Android,Windows-based computer,1.0,1,0,0,0,...,0,No,"No Python, but I've done some programming in o...",1,2.0,1.0,8.0,3.0,8.0,Ambivert
163,Talal,Information sciences,Sophomore,iPhone,Windows-based computer,1.0,0,1,0,0,...,0,Yes,"No Python, but I've done some programming in o...",0,3.0,2.0,8.0,12.0,25.0,Ambivert
165,Anisha,Mcb,Junior,iPhone,Mac OS X-based computer,1.0,0,0,0,0,...,0,Yes,Some Python -- I have had one class or written...,1,4.0,1.0,7.0,6.0,15.0,Introvert

In [40]:
## == TEST CASES for Puzzle 2.2 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(len(df_no_twitch) == 145), "The dataframe does not appear to have been correct subset"

## 2.3: Average Number of Pairs of Shoes

Find the average number of pairs of shoes of each group:

In [41]:
twitch_avg_shoes = df_twitch['Shoes Owned'].mean()
twitch_avg_shoes

4.904761904761905

In [42]:
## == TEST CASES for Puzzle 2.3 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(twitch_avg_shoes == 103/21),  "The average number of pairs of shoes in twitch dataset does not appear to seem correct. Make sure you are taking mean of the correct variable."

In [43]:
no_twitch_avg_shoes = df_no_twitch['Shoes Owned'].mean()
no_twitch_avg_shoes

9.38888888888889

In [44]:
## == TEST CASES for Puzzle 2.3 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(no_twitch_avg_shoes == 1352 / 144),  "The average number of pairs of shoes in no twitch dataset does not appear to seem correct. Make sure you are taking mean of the correct variable."

## 2.4. Observations

Answer the next two questions with 1-2 sentences each.  The cells after the question text are editable -- you should double-click and replace the text with your answer:

### Q1: Is there a difference in the number of shoes owned between the two groups?

Yes, there is a difference. The group that uses Twitch owns lesser shoes on average than the group that doesn't use Twitch.

### Q2: What might be some possible confounding variable in this result?

Low income - The target audience of Twitch are mainly teenagers who are not financially independent to buy shoes themselves.

# Finale!

You're almost done -- congratulations!

You need to do two more things:

1. Save your work.  To do this, create a **notebook checkpoint** by using the menu within the notebook to go **File -> Save and Checkpoint**

2. After you have saved and checkpointed, exit this notebook and return to the Data Science Discovery page on how to use git to turn this notebook into the course!