# EC Notebook for Lecture 13: Algorithms

This extra credit Python notebook will let you practice the material you saw in lecture.  Completing all parts of this notebook will earn +1 extra credit point to your grade in STAT 107! :)

This notebook is worth +1 if turned in before 11:30 am on **Friday, Sept. 27** *(30 minutes before the next STAT 107 lecture)*.  You can feel free to complete it anytime for extra practice.

## 1. Loading pandas and importing data

In this extra credit notebook, we will still exploring the information hidden in the "Illini Football" dataset -- as we did in lecture 13 -- to answer some questions.

you can access the "Illini Football" dataset here: 
https://raw.githubusercontent.com/wadefagen/datasets/master/illini-football/illini-football-scores.csv

Next, you need to load the pandas and dataset.

In [16]:
import pandas as pd 

df = pd.read_csv('illini-football-scores.csv')
df

,Season,Date,Location,Opponent,Result,IlliniScore,OpponentScore,Note
0,2018,2018-09-01,vs.,Kent State,W,31,24,NaN
1,2018,2018-09-08,vs.,Western Illinois,W,34,14,NaN
2,2018,2018-09-15,"Chicago, IL",South Florida,L,19,25,NaN
3,2018,2018-09-21,vs.,Penn State,L,24,63,NaN
4,2018,2018-10-06,@,Rutgers,W,38,17,NaN
5,2018,2018-10-13,vs.,Purdue,L,7,46,Homecoming
6,2018,2018-10-20,@,Wisconsin,L,20,49,NaN
7,2018,2018-10-27,@,Maryland,L,33,63,NaN
8,2018,2018-11-03,vs.,Minnesota,W,55,31,NaN
9,2018,2018-11-10,@,Nebraska,L,35,54,NaN
10,2018,2018-11-17,vs.,Iowa,L,0,63,NaN
11,2018,2018-11-24,@,Northwestern,L,16,24,NaN
12,2017,2017-09-02,vs.,Ball State,W,24,21,NaN
13,2017,2017-09-09,vs.,Western Kentucky,W,20,7,NaN
14,2017,2017-09-15,@,South Florida,L,23,47,NaN
15,2017,2017-09-29,vs.,Nebraska,L,6,28,NaN
16,2017,2017-10-07,@,Iowa,L,16,45,NaN
17,2017,2017-10-14,vs.,Rutgers,L,24,35,NaN
18,2017,2017-10-21,@,Minnesota,L,17,24,NaN
19,2017,2017-10-28,vs.,Wisconsin,L,10,24,Homecoming
20,2017,2017-11-04,@,Purdue,L,10,29,NaN
21,2017,2017-11-11,vs.,Indiana,L,14,24,NaN
22,2017,2017-11-18,@,Ohio State,L,14,52,NaN
23,2017,2017-11-25,vs.,Northwestern,L,7,42,NaN
24,2016,2016-09-03,vs.,Murray State,W,52,3,NaN
25,2016,2016-09-10,vs.,North Carolina,L,23,48,NaN
26,2016,2016-09-17,vs.,Western Michigan,L,10,34,NaN
27,2016,2016-10-01,@,Nebraska,L,16,31,NaN
28,2016,2016-10-08,vs.,Purdue,L,31,34,NaN
29,2016,2016-10-15,@,Rutgers,W,24,7,NaN
...,...,...,...,...,...,...,...,...
1207,1895,1895-11-02,vs.,Lake Forest,W,38,0,NaN
1208,1895,1895-11-23,vs.,Northwestern,W,38,4,NaN
1209,1895,1895-11-28,@,Purdue,L,2,6,NaN
1210,1894,1894-10-06,@,Wabash,W,36,6,NaN
1211,1894,1894-10-13,@,Chicago A.C.,L,0,14,NaN
1212,1894,1894-10-20,vs.,Lake Forest,W,54,6,NaN
1213,1894,1894-11-03,vs.,Northwestern,W,66,0,NaN
1214,1894,1894-11-17,vs.,Purdue,L,2,22,NaN
1215,1894,1894-11-24,vs.,Indianapolis Artillery,L,14,18,NaN
1216,1894,1894-11-29,"St. Louis, MO",Pastime A.C.,W,10,0,NaN
1217,1893,1893-09-30,vs.,Wabash,W,60,6,NaN
1218,1893,1893-10-07,@,DePauw,W,14,4,NaN
1219,1893,1893-10-21,@,Northwestern,T,0,0,NaN
1220,1893,1893-10-28,vs.,Chicago A.C.,L,4,10,NaN
1221,1893,1893-11-06,vs.,Oberlin,L,24,34,NaN
1222,1893,1893-11-11,"St. Louis, MO",Pastime A.C.,W,18,16,NaN
1223,1893,1893-11-25,@,Purdue,T,26,26,NaN
1224,1893,1893-11-30,vs.,Lake Forest,T,10,10,NaN
1225,1892,1892-10-08,vs.,Purdue,L,6,12,NaN
1226,1892,1892-10-12,vs.,Northwestern,T,16,16,NaN
1227,1892,1892-10-21,@,Washington,W,22,0,NaN
1228,1892,1892-10-22,"Omaha, NE",Doane,W,20,0,NaN
1229,1892,1892-10-24,@,Nebraska,L,0,6,NaN
1230,1892,1892-10-26,@,Baker,W,26,10,NaN
1231,1892,1892-10-27,@,Kansas,L,4,26,NaN
1232,1892,1892-10-29,@,Kansas City A.C.,W,42,0,NaN
1233,1892,1892-11-05,vs.,Englewood High,W,38,0,NaN
1234,1892,1892-11-16,@,Chicago,L,4,10,NaN
1235,1892,1892-11-18,vs.,DePauw,W,34,0,NaN
1236,1892,1892-11-24,vs.,Chicago,W,28,12,NaN

## 2 Puzzle Questions from Lecture.
We have load the csv dataset to the python, and let us answer some intersting questions according to the information which the dataset provides for us. 

### Question 1:
How many unique opponents have we played against? 
How many times have we played against each opponent?
What is the Illini win-loss record against Purdue and Chicago, (that is Win - Lost)? 
How many homecoming games have we played?
What is our Win-Loss record among homecoming games, (that is Win - Lost)?

In [35]:


group = df.groupby('Opponent')
grouped_count = group.agg('count').reset_index()
uniq_opponent = len(grouped_count['Opponent'])

times_each = df['Opponent'].value_counts()


df_purdue = df[df['Opponent'] == 'Purdue']
df_chicago = df[df['Opponent'] == 'Chicago']
result_p = df_purdue['Result'].value_counts()
result_c = df_chicago['Result'].value_counts()

wins_lost_purdue = result_p[0] - result_p[1]
wins_lost_chicago = result_c[0] - result_c[1]

df_hc = df[df['Note'] == 'Homecoming']
num_homecoming = len(df_hc)

result_hc = df_hc['Result'].value_counts()
wins_lost_homecoming = result_hc[1] - result_hc[0]



times_each

Northwestern              112
Ohio State                103
Michigan                   95
Purdue                     93
Wisconsin                  85
Iowa                       74
Minnesota                  71
Indiana                    71
Michigan State             46
Chicago                    43
Penn State                 24
Missouri                   24
Washington                 20
Nebraska                   16
Southern California        13
Notre Dame                 12
Syracuse                   12
UCLA                       12
Stanford                   10
California                 10
Butler                      9
Bradley                     8
Army                        8
Pittsburgh                  8
Wabash                      8
Washington State            7
Knox                        7
Physicians & Surgeons       7
Western Michigan            6
Iowa State                  6
                         ...
Florida A&M                 1
Oklahoma                    1
Youngstown State            1
South Dakota State          1
Baker                       1
Akron                       1
Oregon State                1
Doane                       1
Marquette                   1
Chicago Dental              1
Louisiana-Lafayette         1
Kansas City A.C.            1
Utah State                  1
Texas State                 1
Charleston Southern         1
Navy                        1
Kansas State                1
Alabama                     1
Illinois College            1
Camp Funston                1
Murray State                1
Chicago Naval Reserve       1
Iowa Pre-Flight             1
Indianapolis Artillery      1
Louisiana State             1
Hawaii                      1
Clemson                     1
Chanute Field               1
Christian Brothers          1
North Division High         1
Name: Opponent, Length: 131, dtype: int64

In [34]:
## == TEST CASES for Question 1 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(uniq_opponent  == 131), "The unique opponent number does not appear correct."
assert(times_each[0] == 2), "The times against each opponent does not appear correct."
assert(wins_lost_chicago == 4), "The wins - lost against Chicago does not appear correct."
assert(num_homecoming == 108), "The number of Homecoming does not appear correct."
assert(wins_lost_homecoming == -18), "The wins - lost at Homecoming does not appear correct."

AssertionError: The times against each opponent does not appear correct.

## 3 Algorithm
When we analyze the dataset, we are only curious about some certain columns of the dataset, so it is intuitively to subset the whoel dataset by removing some columns or just select some columns. 


### Question 2:
Try to subset the "df" dataset as a new dataset called "dfnew" which dose not include "Season", "Date", "Note".
Now, I believe you have got the dataset "dfnew", let us calculate the mean, median and standard deviation for IlliniScore at home ("vs.")

In [36]:
dfnew = df.drop(columns=['Season','Date','Note'])
dfnew_home = dfnew[dfnew['Location'] == 'vs.']
mean = dfnew_home['IlliniScore'].mean()
median = dfnew_home['IlliniScore'].median()
sd = dfnew_home['IlliniScore'].std()

In [37]:
## == TEST CASES for Question 2 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(round(mean,0)  == 21.0), "The mean of IlliniScore at home does not appear correct."
assert(median == 20), "The median of IlliniScore at home does not appear correct."
assert(round(sd,0) == 16.0), "The standard deviation of IlliniScore at home does not appear correct."